params:
  training_experiment: baselines.train_iqr_ad
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: ExathlonDataset
training_param_updates:
  dataset:
    name: ExathlonDataset
  training:
    epochs: 1
detector_param_grid:
  detector_params:
    std_factor:
      - 1.28
      - 1.64
      - 1.96
      - 2.33
      - 2.58
      - 3.09
    first_diffs:
      - True
      - False
    cum_method:
      - mean
      - max
    feature_index:
      - null
      - 0
      - 1
      - 2
      - 3
      - 4
      - 5
      - 6
      - 7
      - 8
      - 9
      - 10
      - 11
      - 12
      - 13
      - 14
      - 15
      - 16
      - 17
      - 18
