params:
  training_experiment: reconstruction.train_lstm_ae
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: ExathlonDataset
training_param_updates:
  dataset:
    name: ExathlonDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    hidden_dimensions:
      - [30]
      - [40]
      - [50]
      - [30, 30]
      - [50, 50]
      - [50, 50, 30]
      - [100, 50, 50]
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 25
            - 50
            - 75
            - 100
            - 150
  training:
    optimizer:
      args:
        lr:
          - 0.5e-4
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
