params:
  training_experiment: reconstruction.train_tcn_ae
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    nb_filters:
      - 20
      - 30
      - 40
#    dropout_rate:
#      - 0.0
#      - 0.1
#      - 0.2
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 100
            - 120
            - 150
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
