params:
  training_experiment: reconstruction.train_mscred
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    c_out:
      - 128
#      - 192
      - 256
#    small_model:
#      - False
#    chi:
#      - 5.0
  dataset:
    pipeline:
      window:
        args:
          wins:
            - [10, 30, 60]
            - [10, 50, 100]
#          seg_interval:
#            - 10
          h:
            - 5
            - 10
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
#detector_param_grid:
#  detector:
#    - models.reconstruction.MSCREDAnomalyDetector
#    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
#      args:
#        error_threshold: 0.5
