params:
  training_experiment: reconstruction.train_usad
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    z_size:
      - 30
      - 40
      - 50
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
#            - 20
#            - 30
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
#detector_param_grid:
#  detector_params:
#    alpha:
#      - 0.0
#      - 0.2
#      - 0.5
#      - 0.7
#      - 1.0
