params:
  training_experiment: reconstruction.train_stgat_mad
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    embed_dim:
      - null
      - 50
      - 100
    layer_numb:
      - 2
      - 3
      - 4
    lstm_n_layers:
      - 1
      - 2
    recon_n_layers:
      - 1
      - 2
    recon_hid_dim:
      - 100
      - 150
      - 200
#    dropout:
#      - 0.2
#    alpha:
#      - 0.2
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
