params:
  training_experiment: generative.vae.train_gmm_vae
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    gru_hidden_dims:
      - [60]
    latent_dim:
      - 8
      - 20
    gmm_components:
      - 2
      - 10
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
detector_param_grid:
  detector_params:
    num_mc_samples:
      - 2
      - 64
