params:
  training_experiment: prediction.train_gdn
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    dim:
      - 64
    out_layer_hidden_dims:
      - [64]
      - [64, 64]
    topk:
      - 15
      - 30
    dropout_prob:
      - 0.2
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 5
            - 10
            - 25
          prediction_horizon:
            - 1
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
