params:
  training_experiment: prediction.train_lstm_prediction_filonov
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [30, 20]
    linear_hidden_layers:
      - []
      - [40]
    dropout:
      - 0.0
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 10
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
