params:
  training_experiment: prediction.train_tcn_prediction_he
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: ExathlonDataset
training_param_updates:
  dataset:
    name: ExathlonDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    filters:
      - [32, 32, 32, 32, 32]
      - [32, 32, 64, 64, 64]
      - [64, 64, 64, 64, 64]
    kernel_sizes:
      - [3, 3, 3, 3, 3]
      - [5, 5, 5, 5, 5]
      - [5, 5, 5, 3, 3]
    dilations:
      - [1, 2, 4, 8, 16]
    last_n_layers_to_cat:
      - 2
      - 3
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
#      prediction:
#        args:
#          offset:
#            - 1
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
