params:
  training_experiment: generative.gan.train_lstm_vae_gan
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [60]
    latent_dim:
      - 10
      - 35
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
detector_param_grid:
  detector_params:
    alpha:
      - 0.1
      - 0.3
      - 0.5
      - 0.7
      - 0.9
