params:
  training_experiment: generative.vae.train_donut
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    hidden_dims:
      - [100, 100]
      - [100, 100, 100]
    latent_dim:
      - 20
      - 50
    mask_prob:
      - 0.01
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
detector_param_grid:
  detector_params:
    num_mc_samples:
      - 2
      - 64
