params:
  training_experiment: other.train_ncad
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  dataset:
    name: SWaTDataset
  training:
#    epochs: 100
    epochs: 1
    batch_size: 32
    drop_last: True
training_param_grid:
  model_params:
    suspect_window_length:
      - 1
      - 5
#    tcn_kernel_size:
#      - 7
    tcn_layers:
      - 5
      - 8
#    tcn_out_channels:
#      - 20
#    tcn_maxpool_out_channels:
#      - 8
#    embedding_rep_dim:
#      - 120
#    normalize_embedding:
#      - True
#    distance:
#      - l2_distance
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
    trainer:
      args:
        coe_rate:
          - 0.3
          - 1.116
        mixup_rate:
          - 0.5
          - 1.96
