params:
  training_experiment: other.train_mtad_gat
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    gru_hidden_dim:
      - 100
      - 300
#    gru_dropout_prob:
#      - 0.0
    mlp_hidden_dim:
      - [100, 100]
      - [300, 300, 300]
    vae_hidden_dim:
      - 300
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 10
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
#detector_param_grid:
#  detector_params:
#    gamma:
#      - 0.8
