params:
  training_experiment: prediction.train_tcn_prediction_munir
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_f1_score
    - auprc
training_param_updates:
  dataset:
    name: SWaTDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    filters:
      - [32, 32]
      - [64, 64]
    kernel_sizes:
      - [3, 3]
      - [5, 5]
    linear_hidden_layers:
      - [50]
      - [30, 50]
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 10
            - 50
            - 100
          prediction_horizon:
            - 3
            - 10
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
