params:
  training_experiment: prediction.train_lstm_prediction_filonov
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_f1_score
    - auprc
training_param_updates:
  dataset:
    name: SWaTDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [30, 20]
      - [50, 30]
    linear_hidden_layers:
      - []
      - [40]
      - [30, 30]
    dropout:
      - 0.0
      - 0.15
      - 0.2
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
