params:
  training_experiment: generative.gan.train_lstm_vae_gan
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [60]
      - [100, 100]
    latent_dim:
      - 10
      - 50
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
#detector_param_grid:
#  detector_params:
#    alpha:
#      - 0.5
