params:
  training_experiment: generative.gan.train_beatgan
  validation_metric: best_ts_f1_score_classic
  evaluation_metrics:
    - best_ts_f1_score_classic
#    - ts_auprc_unweighted
    - best_f1_score
    - auprc
training_param_updates:
  training:
#    epochs: 100
    epochs: 1
training_param_grid:
  model_params:
    conv_filters:
      - 32
      - 64
    latent_dim:
      - 50
      - 100
#  loss_params:
#    adversarial_weight:
#      - 1.0
  dataset:
    pipeline:
      augmentation:
        args:
#          distort_fraction:
#            - 0.05
          n_augmentations:
            - 0
            - 1
            - 2
#  training:
#    optimizer:
#      args:
#        lr:
#          - 1.0e-4
#          - 1.0e-3
#          - 1.0e-2
