params:
  training_experiment: generative.vae.train_lstm_vae_soelch
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: ExathlonDataset
training_param_updates:
  dataset:
    name: ExathlonDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [60]
      - [128, 128]
    latent_dim:
      - 20
      - 50
    prior_hidden_dim:
      - 20
      - 40
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
          - 1.0e-2
