dataset:
  name: WADIDataset
params:
  training_experiment: reconstruction.train_mscred
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_f1_score
    - auprc
  batch_size: 64
training_param_updates:
  dataset:
    name: WADIDataset
  training:
    epochs: 100
    batch_size: 64
training_param_grid:
  model_params:
    c_out:
      - 256
    small_model:
      - False
    chi:
      - 5.0
  dataset:
    pipeline:
      window:
        args:
          wins:
            - [10, 30, 60]
          seg_interval:
            - 10
          h:
            - 5
  training:
    optimizer:
      args:
        lr:
#          - 1.0e-4
          - 1.0e-3
detector_param_grid:
  detector:
    - models.reconstruction.MSCREDAnomalyDetector
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 0.1
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 0.3
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 0.5
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 0.7
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 0.9
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 1.1
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 1.3
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 1.5
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 1.7
    - class: models.reconstruction.MSCREDAnomalyDetectorOrig
      args:
        error_threshold: 1.9
