dataset:
  name: WADIDataset
params:
  training_experiment: reconstruction.train_dense_ae
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_f1_score
    - auprc
  batch_size: 64
training_param_updates:
  dataset:
    name: WADIDataset
  training:
    epochs: 100
    batch_size: 64
training_param_grid:
  model_params:
    z_size:
      - 20
      - 30
#      - 40
      - 50
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
#            - 25
            - 50
            - 75
            - 100
#            - 150
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
#          - 5.0e-4
          - 1.0e-3
#          - 5.0e-3
          - 1.0e-2
