dataset:
  name: WADIDataset
params:
  training_experiment: prediction.train_lstm_prediction_malhotra
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_f1_score
    - auprc
training_param_updates:
  dataset:
    name: WADIDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    lstm_hidden_dims:
      - [30, 20]
      - [50, 30]
    linear_hidden_layers:
      - []
      - [40]
      - [20, 20]
  dataset:
    pipeline:
      prediction:
        args:
          window_size:
            - 10
            - 50
            - 100
            - 150
          prediction_horizon:
            - 3
            - 10
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
#          - 1.0e-2
