name: TimeSeAD
channels:
  - pytorch
  - defaults
  - conda-forge
  - pyg
dependencies:
  - python=3.9.5
  - pip=21.1.2
  - numpy=1.20.2
  - scikit-learn=0.24.2
  - tqdm=4.59.0
  - matplotlib=3.3.4
  - pandas=1.2.4
  - pytorch=1.9.0
  - torchvision=0.10.0
  - cudatoolkit=10.2
  - openpyxl=3.0.9
  - pymongo=3.12.0
  - pyyaml=6.0
  - pyg=2.0.3
  - pip:
      - pyreadr==0.4.2
      - sacred==0.8.2
