name: TimeSeAD_cuda117
channels:
  - pytorch
  - defaults
  - conda-forge
  - pyg
  - nvidia
dependencies:
  - python=3.9.5
  - pip=23.2.1
  - numpy=1.25.2
  - scikit-learn=1.3.0
  - matplotlib=3.7.2
  - pandas=2.0.3
  - pytorch=2.0.1
  - torchvision=0.15.2
  - pytorch-cuda=11.7
  - pyg=2.3.1
  - pip:
      - pyreadr==0.4.9
      - sacred==0.8.4
