params:
  training_experiment: reconstruction.train_stgat_mad
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    embed_dim:
      - null
    layer_numb:
      - 2
    lstm_n_layers:
      - 1
    recon_n_layers:
      - 1
    recon_hid_dim:
      - 150
      - 200
    dropout:
      - 0.2
    alpha:
      - 0.2
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
