params:
  training_experiment: reconstruction.train_lstm_max_ae
  validation_metric: best_ts_f1_score
  evaluation_metrics:
    - best_ts_f1_score
    - ts_auprc
    - best_ts_f1_score_classic
    - ts_auprc_unweighted
    - best_f1_score
    - auprc
dataset:
  name: SMDDataset
training_param_updates:
  dataset:
    name: SMDDataset
  training:
    epochs: 100
training_param_grid:
  model_params:
    hidden_dimensions:
      - [40]
      - [64]
      - [64, 64]
    latent_pooling:
      - mean
      - max
  dataset:
    pipeline:
      window:
        args:
          window_size:
            - 10
            - 50
            - 100
  training:
    optimizer:
      args:
        lr:
          - 1.0e-4
          - 1.0e-3
